# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'composite_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CompositeViewer(object):
    def setupUi(self, CompositeViewer):
        CompositeViewer.setObjectName("CompositeViewer")
        CompositeViewer.resize(1151, 852)
        self.central_widget = QtWidgets.QWidget(CompositeViewer)
        self.central_widget.setObjectName("central_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.central_widget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rb_lh = QtWidgets.QRadioButton(self.groupBox)
        self.rb_lh.setObjectName("rb_lh")
        self.gridLayout_2.addWidget(self.rb_lh, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.rb_mof = QtWidgets.QRadioButton(self.groupBox)
        self.rb_mof.setObjectName("rb_mof")
        self.gridLayout_2.addWidget(self.rb_mof, 1, 0, 1, 1)
        self.edit_formation_name = QtWidgets.QLineEdit(self.groupBox)
        self.edit_formation_name.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_formation_name.sizePolicy().hasHeightForWidth())
        self.edit_formation_name.setSizePolicy(sizePolicy)
        self.edit_formation_name.setMinimumSize(QtCore.QSize(150, 0))
        self.edit_formation_name.setObjectName("edit_formation_name")
        self.gridLayout_2.addWidget(self.edit_formation_name, 1, 1, 1, 1)
        self.rb_rh = QtWidgets.QRadioButton(self.groupBox)
        self.rb_rh.setObjectName("rb_rh")
        self.gridLayout_2.addWidget(self.rb_rh, 2, 0, 1, 1)
        self.btn_load_composite = QtWidgets.QPushButton(self.groupBox)
        self.btn_load_composite.setObjectName("btn_load_composite")
        self.gridLayout_2.addWidget(self.btn_load_composite, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.central_widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.edit_defense_name = QtWidgets.QLineEdit(self.groupBox_2)
        self.edit_defense_name.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_defense_name.sizePolicy().hasHeightForWidth())
        self.edit_defense_name.setSizePolicy(sizePolicy)
        self.edit_defense_name.setMinimumSize(QtCore.QSize(150, 0))
        self.edit_defense_name.setObjectName("edit_defense_name")
        self.gridLayout_3.addWidget(self.edit_defense_name, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.btn_load_defense = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_load_defense.setObjectName("btn_load_defense")
        self.gridLayout_3.addWidget(self.btn_load_defense, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.scroll_field = QtWidgets.QScrollArea(self.central_widget)
        self.scroll_field.setWidgetResizable(True)
        self.scroll_field.setObjectName("scroll_field")
        self.widget_formation_visualization = QtWidgets.QWidget()
        self.widget_formation_visualization.setGeometry(QtCore.QRect(0, 0, 1129, 669))
        self.widget_formation_visualization.setStyleSheet("background-color: white;")
        self.widget_formation_visualization.setObjectName("widget_formation_visualization")
        self.scroll_field.setWidget(self.widget_formation_visualization)
        self.gridLayout.addWidget(self.scroll_field, 1, 0, 1, 3)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        CompositeViewer.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(CompositeViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1151, 21))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        CompositeViewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CompositeViewer)
        self.statusbar.setObjectName("statusbar")
        CompositeViewer.setStatusBar(self.statusbar)
        self.actionSave_Library = QtWidgets.QAction(CompositeViewer)
        self.actionSave_Library.setObjectName("actionSave_Library")
        self.actionExit = QtWidgets.QAction(CompositeViewer)
        self.actionExit.setObjectName("actionExit")
        self.menu_file.addAction(self.actionExit)
        self.menubar.addAction(self.menu_file.menuAction())

        self.retranslateUi(CompositeViewer)
        self.actionExit.triggered.connect(CompositeViewer.close)
        QtCore.QMetaObject.connectSlotsByName(CompositeViewer)

    def retranslateUi(self, CompositeViewer):
        _translate = QtCore.QCoreApplication.translate
        CompositeViewer.setWindowTitle(_translate("CompositeViewer", "MainWindow"))
        self.groupBox.setTitle(_translate("CompositeViewer", "Offense"))
        self.rb_lh.setText(_translate("CompositeViewer", "LH"))
        self.label_5.setText(_translate("CompositeViewer", "Formation Name"))
        self.rb_mof.setText(_translate("CompositeViewer", "MOF"))
        self.rb_rh.setText(_translate("CompositeViewer", "RH"))
        self.btn_load_composite.setText(_translate("CompositeViewer", "Load Formation"))
        self.groupBox_2.setTitle(_translate("CompositeViewer", "Defense"))
        self.label_6.setText(_translate("CompositeViewer", "Defense Name"))
        self.btn_load_defense.setText(_translate("CompositeViewer", "Load Formation"))
        self.menu_file.setTitle(_translate("CompositeViewer", "File"))
        self.actionSave_Library.setText(_translate("CompositeViewer", "Save Library"))
        self.actionSave_Library.setShortcut(_translate("CompositeViewer", "Ctrl+S"))
        self.actionExit.setText(_translate("CompositeViewer", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CompositeViewer = QtWidgets.QMainWindow()
    ui = Ui_CompositeViewer()
    ui.setupUi(CompositeViewer)
    CompositeViewer.show()
    sys.exit(app.exec_())
