# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'defense_editor.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DefensiveEditor(object):
    def setupUi(self, DefensiveEditor):
        DefensiveEditor.setObjectName("DefensiveEditor")
        DefensiveEditor.resize(1151, 852)
        self.central_widget = QtWidgets.QWidget(DefensiveEditor)
        self.central_widget.setObjectName("central_widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter = QtWidgets.QSplitter(self.central_widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.edit_defense_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_defense_name.setObjectName("edit_defense_name")
        self.verticalLayout.addWidget(self.edit_defense_name)
        self.btn_save_defense = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_save_defense.setObjectName("btn_save_defense")
        self.verticalLayout.addWidget(self.btn_save_defense)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.btn_delete_selected_defense = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_delete_selected_defense.setObjectName("btn_delete_selected_defense")
        self.verticalLayout.addWidget(self.btn_delete_selected_defense)
        self.scrollArea = QtWidgets.QScrollArea(self.layoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 392, 628))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.list_defenses = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.list_defenses.setObjectName("list_defenses")
        self.gridLayout_3.addWidget(self.list_defenses, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.layoutWidget1)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.widget_formation_visualization = QtWidgets.QWidget()
        self.widget_formation_visualization.setGeometry(QtCore.QRect(0, 0, 723, 411))
        self.widget_formation_visualization.setStyleSheet("background-color: white;")
        self.widget_formation_visualization.setObjectName("widget_formation_visualization")
        self.scrollArea_2.setWidget(self.widget_formation_visualization)
        self.gridLayout_4.addWidget(self.scrollArea_2, 2, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.combo_personnel_grouping = QtWidgets.QComboBox(self.groupBox_2)
        self.combo_personnel_grouping.setMinimumSize(QtCore.QSize(150, 0))
        self.combo_personnel_grouping.setObjectName("combo_personnel_grouping")
        self.gridLayout.addWidget(self.combo_personnel_grouping, 0, 1, 1, 1)
        self.cb_d1 = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_d1.setChecked(False)
        self.cb_d1.setObjectName("cb_d1")
        self.gridLayout.addWidget(self.cb_d1, 1, 0, 1, 1)
        self.cb_d7 = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_d7.setObjectName("cb_d7")
        self.gridLayout.addWidget(self.cb_d7, 1, 1, 1, 1)
        self.cb_d2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_d2.setObjectName("cb_d2")
        self.gridLayout.addWidget(self.cb_d2, 2, 0, 1, 1)
        self.cb_d8 = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_d8.setObjectName("cb_d8")
        self.gridLayout.addWidget(self.cb_d8, 2, 1, 1, 1)
        self.cb_d3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_d3.setObjectName("cb_d3")
        self.gridLayout.addWidget(self.cb_d3, 3, 0, 1, 1)
        self.cb_d9 = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_d9.setObjectName("cb_d9")
        self.gridLayout.addWidget(self.cb_d9, 3, 1, 1, 1)
        self.cb_d4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_d4.setObjectName("cb_d4")
        self.gridLayout.addWidget(self.cb_d4, 4, 0, 1, 1)
        self.cb_d10 = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_d10.setObjectName("cb_d10")
        self.gridLayout.addWidget(self.cb_d10, 4, 1, 1, 1)
        self.cb_d5 = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_d5.setObjectName("cb_d5")
        self.gridLayout.addWidget(self.cb_d5, 5, 0, 1, 1)
        self.cb_d11 = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_d11.setObjectName("cb_d11")
        self.gridLayout.addWidget(self.cb_d11, 5, 1, 1, 1)
        self.cb_d6 = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_d6.setObjectName("cb_d6")
        self.gridLayout.addWidget(self.cb_d6, 6, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rb_lh = QtWidgets.QRadioButton(self.groupBox)
        self.rb_lh.setObjectName("rb_lh")
        self.gridLayout_2.addWidget(self.rb_lh, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.rb_mof = QtWidgets.QRadioButton(self.groupBox)
        self.rb_mof.setObjectName("rb_mof")
        self.gridLayout_2.addWidget(self.rb_mof, 1, 0, 1, 1)
        self.edit_formation_name = QtWidgets.QLineEdit(self.groupBox)
        self.edit_formation_name.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_formation_name.sizePolicy().hasHeightForWidth())
        self.edit_formation_name.setSizePolicy(sizePolicy)
        self.edit_formation_name.setMinimumSize(QtCore.QSize(150, 0))
        self.edit_formation_name.setObjectName("edit_formation_name")
        self.gridLayout_2.addWidget(self.edit_formation_name, 1, 1, 1, 1)
        self.rb_rh = QtWidgets.QRadioButton(self.groupBox)
        self.rb_rh.setObjectName("rb_rh")
        self.gridLayout_2.addWidget(self.rb_rh, 2, 0, 1, 1)
        self.btn_load_composite = QtWidgets.QPushButton(self.groupBox)
        self.btn_load_composite.setObjectName("btn_load_composite")
        self.gridLayout_2.addWidget(self.btn_load_composite, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 1, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.layoutWidget1)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.widget_defense_entry = QtWidgets.QWidget()
        self.widget_defense_entry.setGeometry(QtCore.QRect(0, 0, 413, 355))
        self.widget_defense_entry.setObjectName("widget_defense_entry")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_defense_entry)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_defense_entry)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.combo_defender_to_edit = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_defender_to_edit.sizePolicy().hasHeightForWidth())
        self.combo_defender_to_edit.setSizePolicy(sizePolicy)
        self.combo_defender_to_edit.setObjectName("combo_defender_to_edit")
        self.horizontalLayout.addWidget(self.combo_defender_to_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.frame_defender_edit = QtWidgets.QFrame(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_defender_edit.sizePolicy().hasHeightForWidth())
        self.frame_defender_edit.setSizePolicy(sizePolicy)
        self.frame_defender_edit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_defender_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_defender_edit.setObjectName("frame_defender_edit")
        self.verticalLayout_2.addWidget(self.frame_defender_edit)
        self.gridLayout_7.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.widget_defense_entry)
        self.gridLayout_4.addWidget(self.scrollArea_3, 0, 1, 2, 1)
        self.gridLayout_5.addWidget(self.splitter, 0, 0, 1, 1)
        DefensiveEditor.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(DefensiveEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1151, 26))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        DefensiveEditor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DefensiveEditor)
        self.statusbar.setObjectName("statusbar")
        DefensiveEditor.setStatusBar(self.statusbar)
        self.actionSave_Library = QtWidgets.QAction(DefensiveEditor)
        self.actionSave_Library.setObjectName("actionSave_Library")
        self.actionExit = QtWidgets.QAction(DefensiveEditor)
        self.actionExit.setObjectName("actionExit")
        self.menu_file.addAction(self.actionSave_Library)
        self.menu_file.addAction(self.actionExit)
        self.menubar.addAction(self.menu_file.menuAction())

        self.retranslateUi(DefensiveEditor)
        self.actionExit.triggered.connect(DefensiveEditor.close)
        QtCore.QMetaObject.connectSlotsByName(DefensiveEditor)

    def retranslateUi(self, DefensiveEditor):
        _translate = QtCore.QCoreApplication.translate
        DefensiveEditor.setWindowTitle(_translate("DefensiveEditor", "MainWindow"))
        self.label.setText(_translate("DefensiveEditor", "Defense Name:"))
        self.btn_save_defense.setText(_translate("DefensiveEditor", "Save Defense"))
        self.label_2.setText(_translate("DefensiveEditor", "Defense"))
        self.btn_delete_selected_defense.setText(_translate("DefensiveEditor", "Delete Selected Defense"))
        self.groupBox_2.setTitle(_translate("DefensiveEditor", "Affected Personnel"))
        self.label_4.setText(_translate("DefensiveEditor", "Personnel Groupings:"))
        self.cb_d1.setText(_translate("DefensiveEditor", "D1"))
        self.cb_d7.setText(_translate("DefensiveEditor", "D7"))
        self.cb_d2.setText(_translate("DefensiveEditor", "D2"))
        self.cb_d8.setText(_translate("DefensiveEditor", "D8"))
        self.cb_d3.setText(_translate("DefensiveEditor", "D3"))
        self.cb_d9.setText(_translate("DefensiveEditor", "D9"))
        self.cb_d4.setText(_translate("DefensiveEditor", "D4"))
        self.cb_d10.setText(_translate("DefensiveEditor", "D10"))
        self.cb_d5.setText(_translate("DefensiveEditor", "D5"))
        self.cb_d11.setText(_translate("DefensiveEditor", "D11"))
        self.cb_d6.setText(_translate("DefensiveEditor", "D6"))
        self.groupBox.setTitle(_translate("DefensiveEditor", "Offense"))
        self.rb_lh.setText(_translate("DefensiveEditor", "LH"))
        self.label_5.setText(_translate("DefensiveEditor", "Formation Name"))
        self.rb_mof.setText(_translate("DefensiveEditor", "MOF"))
        self.rb_rh.setText(_translate("DefensiveEditor", "RH"))
        self.btn_load_composite.setText(_translate("DefensiveEditor", "Load Formation"))
        self.groupBox_3.setTitle(_translate("DefensiveEditor", "Defender Edit"))
        self.label_3.setText(_translate("DefensiveEditor", "Defender:"))
        self.label_6.setText(_translate("DefensiveEditor", "Condtions"))
        self.label_7.setText(_translate("DefensiveEditor", "Alignment Rules"))
        self.menu_file.setTitle(_translate("DefensiveEditor", "File"))
        self.actionSave_Library.setText(_translate("DefensiveEditor", "Save Library"))
        self.actionSave_Library.setShortcut(_translate("DefensiveEditor", "Ctrl+S"))
        self.actionExit.setText(_translate("DefensiveEditor", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DefensiveEditor = QtWidgets.QMainWindow()
    ui = Ui_DefensiveEditor()
    ui.setupUi(DefensiveEditor)
    DefensiveEditor.show()
    sys.exit(app.exec_())
